"""Core of the combined video-enhance node: plan, DNR3 protocol, DLSS worker.

Nothing here imports ComfyUI, so the whole slice is unit testable on its own.
The DLSS stages run in one external worker process per execution
(`my_nodes.core.video_enhance.dlss_worker`), which speaks the DNR3 protocol to
the vendored native host (`my_nodes/core/video_enhance/native`).
"""

from .dlss_worker import Dnr3Worker
from .dnr3 import (
    END_MAGIC,
    END_SIZE,
    FEATURE_MASK,
    FEATURE_NR,
    FEATURE_SR,
    FRAME_HEADER_SIZE,
    FRAME_MAGIC,
    HEADER_SIZE,
    MAGIC,
    MAX_DIM,
    MAX_FRAMES,
    NATIVE_PERF_QUALITY,
    PERF_QUALITY_RATIOS,
    RATIO_TOLERANCE,
    REPLY_HEADER_SIZE,
    REPLY_MAGIC,
    SR_SCALE_PERF_QUALITY,
    Dnr3Error,
    Dnr3ProtocolError,
    Dnr3RemoteError,
    Dnr3ValidationError,
    Header,
    check_features,
    decode_rgb,
    motion_payload,
    perf_quality_for_scale,
    rgb_payload,
)
from .plan import (
    CUSTOM_NR_PROFILE,
    GPU_INDEX_RANGE,
    INTERPOLATION_FACTORS,
    NR_COLOR_RANGE,
    NR_DETAIL_RANGE,
    NR_INTENSITY_RANGE,
    NR_LOCAL_STRUCTURE_RANGE,
    NR_LOCAL_TONE_RANGE,
    NR_PRESETS,
    NR_PROFILES,
    NR_SKIN_RANGE,
    NR_STYLES,
    SR_PRESETS,
    SR_SCALES,
    STAGE_DLSS,
    STAGE_VFI,
    VideoEnhancePlan,
)
from .runtime import (
    CORE_DLL,
    NR_DLL,
    NR_DLL_RTX30,
    SR_DLL,
    HostDriver,
    RuntimeFileError,
    RuntimeFiles,
    build_environment,
    check_wine_prefix,
    find_wine,
    host_executable,
    resolve_runtime_files,
    resolve_wine_prefix,
)
from .scoped_process import (
    ProcessError,
    ProcessInterrupted,
    ProcessIOError,
    ProcessTimeout,
    ScopedProcess,
)

__all__ = [
    "CORE_DLL",
    "CUSTOM_NR_PROFILE",
    "END_MAGIC",
    "END_SIZE",
    "FEATURE_MASK",
    "FEATURE_NR",
    "FEATURE_SR",
    "FRAME_HEADER_SIZE",
    "FRAME_MAGIC",
    "GPU_INDEX_RANGE",
    "HEADER_SIZE",
    "INTERPOLATION_FACTORS",
    "MAGIC",
    "MAX_DIM",
    "MAX_FRAMES",
    "NATIVE_PERF_QUALITY",
    "NR_COLOR_RANGE",
    "NR_DETAIL_RANGE",
    "NR_DLL",
    "NR_DLL_RTX30",
    "NR_INTENSITY_RANGE",
    "NR_LOCAL_STRUCTURE_RANGE",
    "NR_LOCAL_TONE_RANGE",
    "NR_PRESETS",
    "NR_PROFILES",
    "NR_SKIN_RANGE",
    "NR_STYLES",
    "PERF_QUALITY_RATIOS",
    "RATIO_TOLERANCE",
    "REPLY_HEADER_SIZE",
    "REPLY_MAGIC",
    "SR_DLL",
    "SR_PRESETS",
    "SR_SCALES",
    "SR_SCALE_PERF_QUALITY",
    "STAGE_DLSS",
    "STAGE_VFI",
    "Dnr3Error",
    "Dnr3ProtocolError",
    "Dnr3RemoteError",
    "Dnr3ValidationError",
    "Dnr3Worker",
    "Header",
    "HostDriver",
    "ProcessError",
    "ProcessInterrupted",
    "ProcessIOError",
    "ProcessTimeout",
    "RuntimeFileError",
    "RuntimeFiles",
    "ScopedProcess",
    "VideoEnhancePlan",
    "build_environment",
    "check_features",
    "check_wine_prefix",
    "decode_rgb",
    "find_wine",
    "host_executable",
    "motion_payload",
    "perf_quality_for_scale",
    "resolve_runtime_files",
    "resolve_wine_prefix",
    "rgb_payload",
]
